In [ ]:
Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет 
array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [6]:
import numpy as np

def reverse_arr(N):
  lst = []
  while N > 0:
    N -=1;
    lst.append(N)
  arr = np.array(lst)
  return arr

count = 5
arr = reverse_arr(count)
print(arr)

[4 3 2 1 0]


In [ ]:
Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [8]:
import numpy as np

def reverse_arr(N):
  lst = []
  while N > 0:
    N -=1;
    lst.append(N)
  arr = np.array(lst)
  return arr

count = 6
arr = reverse_arr(count)
Z = np.diag(arr)
print(Z)
diag = np.diag(Z)
print(np.sum(diag))

[[5 0 0 0 0 0]
 [0 4 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 0]]
15


In [ ]:
Задание 3 Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [4]:
import numpy as np
from numpy import linalg as LA

a = [
     [4, 2, 1],
     [1, 3, 0],
     [0, 5, 4]
    ]

b = [4, 12, -3]
x = LA.solve(a, b)
print(x)

[ 0.46666667  3.84444444 -5.55555556]


In [ ]:
Задача 4 домашнего задания

Найдите самого похожего пользователя. 
Т. е. посчитайте косинусное сходство между этим 
пользователем и всеми пользователями из массива user_stats

In [3]:
import numpy
def cosine( users_stats, next_user_stats ):
    users_stats_Length = np.linalg.norm( users_stats )
    next_user_stats_Length = np.linalg.norm( next_user_stats )
    
    return np.dot( users_stats, next_user_stats ) / ( users_stats_Length * next_user_stats_Length )
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])
muls = np.apply_along_axis(cosine, 1, users_stats, next_user_stats)
print("Самое лучшее сходство с " + str(np.argmax(muls)) + " пользователем.")

Самое лучшее сходство с 7 пользователем.
